name: Release and deploy

on: 
  pull_request:
    types: [closed]
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - uses: krogon/semver-release-action@master
      name: Calculate release version
      id: release_version
      with:
        default_increment: patch
        release_branch: main
        release_strategy: none
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.release_version.outputs.tag }}
        release_name: ${{ github.event.pull_request.title }}

    - name: Build container
      run: docker build . -t lkjaero/language-service:latest
    
    - name: Enforce security rules
      uses: anchore/scan-action@v3.2.0
      id: scan
      with:
        image: "lkjaero/language-service:latest"
        acs-report-enable: true
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1.14.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Push production docker image
      run: |
        docker tag lkjaero/language-service:latest lkjaero/language-service:${{ steps.release_version.outputs.tag }}
        docker push lkjaero/language-service:${{ steps.release_version.outputs.tag }}
        docker push lkjaero/language-service:latest

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Save kubeconfig
      run: aws eks --region us-west-2 update-kubeconfig --name fluentlabsprod

    - name: Update image in K8s
      run: |
        kubectl set image deployment/language-service language-service=lkjaero/language-service:${{ steps.release_version.outputs.tag }} --record

    - name: Wait for deployment to finish
      run: |
        kubectl rollout status deployment/language-service