name: Test language-service

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    # - uses: brpaz/hadolint-action@v1.5.0
    #   name: Lint container image
    #   with:
    #     dockerfile: Dockerfile

    - name: Build container
      run: docker build . -t language
    
    - name: Enforce security rules
      uses: anchore/scan-action@v3.2.0
      id: scan
      with:
        image: "language:latest"
        acs-report-enable: true

    - name: Upload scan report
      if: ${{ always() }}
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ steps.scan.outputs.sarif }}

  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.4.0

    - name: Set up Python 3.10
      uses: actions/setup-python@v2.3.2
      with:
        python-version: 3.10.1

    - name: Install package manager
      uses: abatilo/actions-poetry@v2.1.4
      with:
        poetry-version: 1.1.4

    - name: Install dependencies
      run: poetry install

    - name: Check for syntax errors
      run: poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

    - name: Test
      run: poetry run pytest

    - name: Lint
      run: |
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        poetry run flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Validate code formatter
      run: poetry run black . --check

    - name: Code security check
      run: poetry run bandit -r language_service/*
